# Generated by Django 5.1.7 on 2025-03-22 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='ufi',
            new_name='pan',
        ),
    ]
