# Generated by Django 5.1.7 on 2025-03-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_ufi_userprofile_pan'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ufid',
            field=models.CharField(default='ssbds1728b', max_length=10, unique=True),
        ),
    ]
