# Generated by Django 5.1.7 on 2025-03-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_ufid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ufid',
            field=models.CharField(default='ssbds1728b', max_length=10),
        ),
    ]
