# Generated by Django 5.1.7 on 2025-03-22 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_userprofile_ufid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='ufid',
        ),
    ]
