# Generated by Django 5.1.7 on 2025-03-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_userprofile_ufid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ufid',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
