# Generated by Django 5.1.7 on 2025-03-22 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_ufid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='ufid',
        ),
    ]
