# Generated by Django 5.1.7 on 2025-03-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_userprofile_ufid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='pan',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ufi',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
