# Generated by Django 5.1.7 on 2025-03-22 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_userprofile_pan_userprofile_ufi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='ufi',
            new_name='ufid',
        ),
    ]
