# Generated by Django 5.1.7 on 2025-03-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_ufi_userprofile_ufid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pan',
            field=models.CharField(default='hello', max_length=11, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ufid',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
